### ISSUE TITLE
Organisation Ownership

### ISSUE THREAD

**Issue by mnot** [ietf-gitwg/using-github#10]
> Each organization requires owners. The owner team for a working group repository MUST include responsible Area Directors. Area Directors MAY also designate a delegate that becomes an owner and working group chairs MAY also be owners.

Unfortunately, GitHub now only gives the choice between Owners being able to create repos, and all members being able to create repos (see [here](https://help.github.com/en/articles/restricting-repository-creation-in-your-organization)). I don't think the latter is workable (we've already had instances when some WG members strongly wanted to create a WG repo for their personal drafts), so this means that the Chairs MUST be owners, unless they're comfortable with allowing anyone in the org to create a repo.

This choice probably needs to be explained explicitly, with description of the options and the affected settings.

> A team with administrator access SHOULD be created for the Working Group Chairs and any Working Group Secretary. Administrator access is preferable, since this does not also include the ability to push to all repositories and ownership does not grant any other significant privileges.

There is no longer any such thing as an "admin team" on GitHub; that was [phased out](https://help.github.com/en/articles/migrating-your-previous-admin-teams-to-the-improved-organization-permissions). Instead, you'd need to create a separate 'Chairs' team and then assign it admin permissions on each repo.

In practice, Chairs need the ability to push to all repositories, to do things like update READMEs, etc. So I think being owners is appropriate (and it avoids a lot of busy work for the AD in terms of setting things up).

**Comment by martinthomson** [comment]
> GitHub now only gives the choice between Owners being able to create repos, and all members being able to create repos 

I think that you are confusing the technical safeguards on the process from the practical ones.

Giving members (i.e., editors) the ability to create repos is necessary to migrate newly adopted drafts into the org.  Having the chairs create a repo and then have it populated is an awful solution.  So I think that we need this capability and we simply need to explain that creating a repo is not acceptable.

> There is no longer any such thing as an "admin team" on GitHub

The text says "team with administrator access".  Is that unclear?

> I think being owners is appropriate (and it avoids a lot of busy work for the AD in terms of setting things up)

Part of the point of the working group is to feed requirements into tools.  One of those tools we've already discussed is an automated setup process.  So I don't think busy work is necessary.

That said, I have no issue with chairs having commit access to repos.  Like with members creating repos, we'll know when they abuse that power.

**Comment by mnot** [comment]
> I think that you are confusing the technical safeguards on the process from the practical ones.

I tried to read the document and apply it to GitHub. If that ends me up in a confused state, perhaps the document isn't communicating clearly.

> Giving members (i.e., editors) the ability to create repos is necessary to migrate newly adopted drafts into the org. Having the chairs create a repo and then have it populated is an awful solution. 

This is not how httpwg or quicwg works, so I'm surprised to hear you say that; you haven't brought it up before AFAIK.

> So I think that we need this capability and we simply need to explain that creating a repo is not acceptable.

Sorry, what do you mean here?

**Comment by martinthomson** [comment]
> This is not how httpwg or quicwg works, so I'm surprised to hear you say that; you haven't brought it up before AFAIK.

Well, those are both weird.  httpwg has a single repo, which means that it is very hard to import existing work.  quicwg is not operating in a mode where adoption is common.  But everywhere else I've been it is common for things to move from individual to WG drafts on a semi-regular basis.  Moving repos is the method I've been [advocating for](https://github.com/martinthomson/i-d-template/blob/master/doc/ADOPTING.md#best-option---transfer-the-repository) for a while.

I see your point about teams.  That needs to be clearer.
