### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by gregbo** [ietf-gitwg/using-github#11]
using-github/CONTRIBUTING.md has several broken links:

- https://mailarchive.ietf.org/arch/browse/github/ (should be https://mailarchive.ietf.org/arch/browse/ietf-and-github/)

- https://www.ietf.org/mailman/listinfo/github (should be https://www.ietf.org/mailman/listinfo/ietf-and-github)

- https://datatracker.ietf.org/wg/github/documents/ (should be https://datatracker.ietf.org/wg/git/documents/)

I corrected the same problem with https://github.com/gregbo/draft-iab-internet-consolidation/blob/patch-1/CONTRIBUTING.md a few days ago.  I'm not completely familiar with the tools that are used to generate these pages, but from what I have seen, there needs to be a configuration option that allows the names of the mailing list, working group, and source of related documents to differ.  Can you change i-d-template/template/CONTRIBUTING.md so WG_NAME is configurable, but defaults to the working group name?

**Comment by martinthomson** [comment]
Thanks for the report @gregbo.  The tool that generates the files relies a lot on conventions, which breaks down occasionally and requires this sort of manual fixing.
