### ISSUE TITLE
Suggest that repositories include links to rendered and rfcdiff versions

### ISSUE THREAD

**Issue by chris-wood** [ietf-gitwg/using-github#19]
This was brought up on the list. Martin's tooling already sets up READMEs with these links, so we might just add a note documenting what's done.

**Comment by martinthomson** [comment]
Is this something more appropriate for ietf-gitwg/draft-ietf-git-github-wg-configuration?  This is more of a process document than something documenting tools and how things are set up.

**Comment by chris-wood** [comment]
Yeah, probably. I'll file it over there!
