### ISSUE TITLE
Discuss use of GitHub for managing charter, sessions

### ISSUE THREAD

**Issue by martinthomson** [ietf-gitwg/using-github#29]
Some working groups use GitHub to manage changes to charters or other working group materials, like agendas and presentations for sessions.  I'd suggest that no great amount of detail is needed because these aren't the primary focus of the document, but it probably should include at least a passing mention of these uses and acknowledge that they are permitted.

**Comment by chris-wood** [comment]
Discussed in Singapore; MT to add text.

**Comment by martinthomson** [comment]
Closed in #30.
