### ISSUE TITLE
Single IETF org

### ISSUE THREAD

**Issue by martinthomson** [ietf-gitwg/using-github#4]
I've been privately lobbied to use a single organization.  There are arguments around IPR notices and control that might make this advisable.  For instance, the W3C process for using GitHub is far more advanced in this regard.

In particular, W3C repositories all have an integrated application that checks that contributors have made the appropriate contribution agreements.  I don't see why this process wouldn't scale out to multiple organizations if the service were available, but we would need to have some discussion about integrating that.  (I also don't know how much manual intervention is needed to identify "non-substantial" contributions, which are somehow exempt from this process.)

**Comment by martinthomson** [comment]
There's some contention about the level to which secretariat involvement in the operation of an organization is necessary.  The sense I got from WG chairs is that they feel that chairs+AD is sufficient, and burdening the secretariat with more responsibilities wouldn't necessarily improve anything.  We'd probably want to understand what the secretariat responsibilities were with respect to operation of an organization.

**Comment by mnot** [comment]
For the record, I'm strongly -1 on this. Having an organisation with hundreds or thousands of repos is asking for confusion. Also, note that the W3C uses many drafts-per-repo, which I believe there are Strong Feelings against in the IETF.

Of course, it's possible to build tools to make prettier / more sane views of this data; the W3C has done that. That's a significant investment, however, and still requires a fair amount of coordination (e.g., the W3C has a [file format](https://github.com/w3c/spec-dashboard) for its repos that lets them scrape information from them).

However, such a mechanism could easily be used across multiple organisations; all we'd need would be a list of orgs to run it against, and that doesn't seem onerous.

**Comment by martinthomson** [comment]
My sense of the pre-working group discussion was that this was ruled out.  Let's see if the chairs concur.

**Comment by martinthomson** [comment]
The feedback on this point was very clear to me.  I'm closing this.
