### ISSUE TITLE
More on technical decision making and venues

### ISSUE THREAD

**Issue by martinthomson** [ietf-gitwg/using-github#8]
The draft has some text on assessing consensus, which includes managing the venue for discussion.  The practice here has evolved a little and so the text should be expanded to reflect that.

The current view is that drafts in early stages can operate with a fair amount of independence in the sense that technical decisions can be made without consulting the list.  That keeps things running smoothly, because you don't want the overhead of list involvement for every tiny technical change.

As the draft already says issues that become contentious need to go to the list.  But the draft says SHOULD rather than MUST, which needs to be corrected.

As documents become more mature, it makes sense to change the model so that the list is involved in more of the decision-making.  For example, QUIC has taken the line that ALL technical changes need to go to the list, which is fairly hard-line.  The goals there were two-fold: reduce the rate of change, and to ensure that the list is involved in all decisions.  The first has been very effective.  It's hard to say whether a hard cutoff like this has been effective, but the general principle is sound.

**Comment by mnot** [comment]
I think these could be couched as suggested workflows, rather than best practices; it's very situational. The most important thing is to clearly document the workflow in use, and consistently use it; having some templates help (as there are a lot of factors to consider).

**Comment by martinthomson** [comment]
Closing this on the basis of #15.
