### ISSUE TITLE
Document header containing important links

### ISSUE THREAD

**Issue by mnot** [ietf-gitwg/using-github#9]
In the git-using WG's I've participated in, it's been proven useful to add a note at the top of drafts in development that link to the draft's repo, issues list, and datatracker status page.

This makes it easier for readers to find important resources.

**Comment by martinthomson** [comment]
I agree that this is useful.  It would be good to have a standard form for this information so that the information can be mechanically inserted.

Is this issue better raised on this draft or for the other draft that focuses more on the mechanics of the interactions?

**Comment by martinthomson** [comment]
Closed in favour of ietf-gitwg/draft-ietf-git-github-wg-configuration#5.
